export const cities = [
  { id: 0, name: "Kyiv" },
  { id: 1, name: "Kharkiv" },
  { id: 2, name: "Odessa" },
  { id: 3, name: "Dnipro" },
  { id: 4, name: "Donetsk" },
  { id: 5, name: "Zaporizhzhia" },
  { id: 6, name: "Lviv" },
  { id: 7, name: "Kryvyi Rih" },
  { id: 8, name: "Mykolaiv" },
  { id: 9, name: "Sevastopol" },
  { id: 10, name: "Mariupol" },
  { id: 11, name: "Luhansk" },
  { id: 12, name: "Vinnytsia" },
  { id: 13, name: "Makiivka" },
  { id: 14, name: "Simferopol" },
  { id: 15, name: "Chernihiv" },
  { id: 16, name: "Kherson" },
];
